p8105\_hw3\_yq2251
================
TritonD
10/12/2019

``` r
library(tidyverse)
```

    ## -- Attaching packages ----------------------------------------- tidyverse 1.2.1 --

    ## v ggplot2 3.2.1     v purrr   0.3.2
    ## v tibble  2.1.3     v dplyr   0.8.3
    ## v tidyr   1.0.0     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.4.0

    ## -- Conflicts -------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(ggridges)
```

    ## 
    ## Attaching package: 'ggridges'

    ## The following object is masked from 'package:ggplot2':
    ## 
    ##     scale_discrete_manual

``` r
library(patchwork)
library(knitr)
```

## Problem 1

``` r
library(p8105.datasets)
data("instacart")
```

## count how many aisles there are

``` r
instacart %>%
  group_by(aisle) %>%
  summarize(aisle_n = n())
```

    ## # A tibble: 134 x 2
    ##    aisle                  aisle_n
    ##    <chr>                    <int>
    ##  1 air fresheners candles    1067
    ##  2 asian foods               7007
    ##  3 baby accessories           306
    ##  4 baby bath body care        328
    ##  5 baby food formula        13198
    ##  6 bakery desserts           1501
    ##  7 baking ingredients       13088
    ##  8 baking supplies decor     1094
    ##  9 beauty                     287
    ## 10 beers coolers             1839
    ## # ... with 124 more rows

## find out which aisle is most popular

``` r
instacart %>%
  group_by(aisle) %>%
  summarize(aisle_n = n())%>%
filter(min_rank(desc(aisle_n)) < 2)
```

    ## # A tibble: 1 x 2
    ##   aisle            aisle_n
    ##   <chr>              <int>
    ## 1 fresh vegetables  150609

There are 134 aisles in total, with “fresh vegetables” as the aisle with
most items ordered from (n=150609).

\#\#Make a plot that shows the number of items ordered in each aisle
with n\>10000

``` r
instacart %>%
  group_by(aisle) %>%
  summarize(aisle_n = n())%>%
filter(aisle_n > 10000)%>%
ggplot(aes(x=aisle, y=aisle_n)) +
  geom_bar(stat="identity") +
  theme(text = element_text(size=12),
         axis.text.x = element_text(angle=90, vjust=0.5)) +
  labs(
    title = "Ordering by aisle plot",
    x = "Aisle",
    y = "Number of items ordered in each aisle",
    caption = "Data from Instacart datasets"
  )
```

![](p8105_hw3_yq2251_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

## make a table for 3 most popular items in each of the aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”

``` r
instacart %>%
  filter(aisle == c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle, product_name) %>% 
  summarize(aisle_n_product = n())%>%
  filter(min_rank(desc(aisle_n_product)) < 4)%>%
  knitr::kable(digits = 0)
```

| aisle                      | product\_name                                   | aisle\_n\_product |
| :------------------------- | :---------------------------------------------- | ----------------: |
| baking ingredients         | Light Brown Sugar                               |               157 |
| baking ingredients         | Organic Vanilla Extract                         |               122 |
| baking ingredients         | Pure Baking Soda                                |               140 |
| dog food care              | Organix Chicken & Brown Rice Recipe             |                13 |
| dog food care              | Organix Grain Free Chicken & Vegetable Dog Food |                14 |
| dog food care              | Original Dry Dog                                |                 9 |
| packaged vegetables fruits | Organic Baby Spinach                            |              3324 |
| packaged vegetables fruits | Organic Blueberries                             |              1692 |
| packaged vegetables fruits | Organic Raspberries                             |              1920 |

\#\#Make a table showing the mean hour of the day at which Pink Lady
Apples and Coffee Ice Cream are ordered on each day of the week; format
this table for human readers (i.e. produce a 2 x 7 table)

``` r
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(product_name,order_dow) %>% 
  summarize(mean_time = mean(order_hour_of_day))%>%
   pivot_wider(
    names_from = order_dow,
    values_from = mean_time) %>% 
  rename(Sunday="0", Monday="1", Tuesday="2", Wednesday="3", Thursday="4", Friday="5", Saturday="6")%>%
  knitr::kable(digits = 0)
```

| product\_name    | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
| :--------------- | -----: | -----: | ------: | --------: | -------: | -----: | -------: |
| Coffee Ice Cream |     14 |     14 |      15 |        15 |       15 |     12 |       14 |
| Pink Lady Apples |     13 |     11 |      12 |        14 |       12 |     13 |       12 |
